
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Fri May 05 21:32:21 EET 2017
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int REL_OP = 17;
  public static final int INCREMENT = 34;
  public static final int CONST = 10;
  public static final int SLASH = 22;
  public static final int CDOTS = 45;
  public static final int CASE = 16;
  public static final int CLOSE_SQUARE = 28;
  public static final int DECREMENT = 43;
  public static final int FOR = 13;
  public static final int MINUS = 32;
  public static final int BAR = 37;
  public static final int TYPE = 4;
  public static final int OPEN_PARAN = 23;
  public static final int ASTRISK = 31;
  public static final int LESS_DASH = 41;
  public static final int COMMA = 18;
  public static final int OPEN_SQUARE = 27;
  public static final int OR_OP = 42;
  public static final int OPEN_CURLY = 25;
  public static final int PLUS = 21;
  public static final int EXCLAMATION = 38;
  public static final int AMBERSAND = 36;
  public static final int IF = 8;
  public static final int DOT = 29;
  public static final int AND_OP = 35;
  public static final int EOF = 0;
  public static final int RETURN = 9;
  public static final int EQUAL = 12;
  public static final int error = 1;
  public static final int PERCENT = 30;
  public static final int SEMI_COLON = 19;
  public static final int BREAK = 44;
  public static final int SHIFT_LEFT = 40;
  public static final int SWITCH = 14;
  public static final int CLOSE_PARAN = 24;
  public static final int IMPORT = 2;
  public static final int COLON = 20;
  public static final int CLOSE_CURLY = 26;
  public static final int ELSE = 7;
  public static final int FUNC = 11;
  public static final int PACKAGE = 3;
  public static final int DEFAULT = 15;
  public static final int STRUCT = 5;
  public static final int STRING_LIT = 48;
  public static final int INT_LIT = 47;
  public static final int SHIFT_RIGHT = 39;
  public static final int VAR = 6;
  public static final int COLON_EQUAL = 33;
  public static final int IDENTIFIER = 46;
}

